### ISSUE TITLE
theme+ 4.4.3 not compatible with meta-palettes 1.9.0

### ISSUE THREAD

**Issue by bytehead** [bit3/contao-theme-plus#89]
`Fatal error: Class 'ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\DcaReadingDataDefinitionBuilder' not found in contao/composer/vendor/bit3/contao-meta-palettes/src/MetaPalettesBuilder.php on line 42`

installed theme+: `bit3/contao-theme-plus @ 4.4.3`
installed meta-palettes: `bit3/contao-meta-palettes @ 1.9.0`

**Comment by bytehead** [comment]
Workaround: require ` "bit3/contao-meta-palettes": "1.8.1"`

**Comment by tristanlins** [comment]
@bytehead I suppose DC General is not installed?!
@discordier why is the class `DcaReadingDataDefinitionBuilder` required by meta palettes when no DCG is installed?

**Comment by tristanlins** [comment]
This is a meta palettes issue, not a Theme+ issue, please follow up https://github.com/bit3/contao-meta-palettes/issues/32

**Comment by bytehead** [comment]
@tristanlins Thanks for checking!

**Comment by tristanlins** [comment]
Fixed in meta-palettes 1.9.1
