### ISSUE TITLE
RuntimeException nach geänderten uploadPath 

### ISSUE THREAD

**Issue by akroii** [bit3/contao-theme-plus#90]
Wenn sie Variable $GLOBALS['TL_CONFIG']['uploadPath'] = 'files'; in der localconfig.php geändert wird (zb.: 'files/static') funktioniert Theme Plus nicht mehr.

Getestet in Contao 3.3.x

**Comment by tristanlins** [comment]
Was genau funktioniert denn nicht mehr? Was kommt als Meldung der RuntimeException?

**Comment by akroii** [comment]
hatte hier schon ein Thema aufgemacht. https://community.contao.org/de/showthread.php?55029-RuntimeException-nach-ge%E4nderten-uploadPath&p=355046#post355046

[15-Jan-2015 16:22:45 Europe/Berlin] 
PHP Warning: filemtime() expects parameter 1 to be a valid path, string given in C:\MAMP\htdocs\ccccc\contao-3.3.7\system\modules\theme-plus\classes\src\Bit3\Contao\ThemePlus\ThemePlus.php on line 1579
#0 [internal function]: __error(2, 'filemtime() exp...', 'C:\\MAMP\\htdocs\\...', 1579, Array)
#1 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\theme-plus\classes\src\Bit3\Contao\ThemePlus\ThemePlus.php(1579): filemtime('\xD0\xE4\x97\xBFo\xEA\x11\xE4\xB3E\x00"M\x82\x1C...')
#2 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\theme-plus\classes\src\Bit3\Contao\ThemePlus\ThemePlus.php(981): Bit3\Contao\ThemePlus\ThemePlus->addAssetsToCollectionFromDatabase(Object(Contao\Model\Collection), 'css', Object(Assetic\Asset\AssetCollection), Array, Object(Assetic\Filter\FilterCollection))
#3 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\theme-plus\classes\src\Bit3\Contao\ThemePlus\ThemePlus.php(688): Bit3\Contao\ThemePlus\ThemePlus->parseStylesheets(Object(Contao\LayoutModel), Array)
#4 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\core\library\Contao\Controller.php(1823): Bit3\Contao\ThemePlus\ThemePlus->hookReplaceDynamicScriptTags('<!DOCTYPE html>...')
#5 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\core\classes\FrontendTemplate.php(99): Contao\Controller::replaceDynamicScriptTags('<!DOCTYPE html>...')
#6 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\core\pages\PageRegular.php(189): Contao\FrontendTemplate->output(true)
#7 C:\MAMP\htdocs\bernutz\contao-3.3.7\index.php(260): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#8 C:\MAMP\htdocs\bernutz\contao-3.3.7\index.php(444): Index->run()
#9 {main}


[15-Jan-2015 16:22:45 Europe/Berlin] 
PHP Warning: is_file() expects parameter 1 to be a valid path, string given in C:\MAMP\htdocs\ccccc\contao-3.3.7\system\modules\assetic\classes\vendor\kriswallsmith\assetic\src\Assetic\Asset\FileAsset.php on line 72
#0 [internal function]: __error(2, 'is_file() expec...', 'C:\\MAMP\\htdocs\\...', 72, Array)
#1 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\assetic\classes\vendor\kriswallsmith\assetic\src\Assetic\Asset\FileAsset.php(72): is_file('C:\\MAMP\\htdocs\\...')
#2 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\theme-plus\classes\src\Bit3\Contao\ThemePlus\ThemePlus.php(230): Assetic\Asset\FileAsset->getLastModified()
#3 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\theme-plus\classes\src\Bit3\Contao\ThemePlus\ThemePlus.php(1581): Bit3\Contao\ThemePlus\ThemePlus::getAssetPath(Object(Assetic\Asset\FileAsset), 'css')
#4 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\theme-plus\classes\src\Bit3\Contao\ThemePlus\ThemePlus.php(981): Bit3\Contao\ThemePlus\ThemePlus->addAssetsToCollectionFromDatabase(Object(Contao\Model\Collection), 'css', Object(Assetic\Asset\AssetCollection), Array, Object(Assetic\Filter\FilterCollection))
#5 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\theme-plus\classes\src\Bit3\Contao\ThemePlus\ThemePlus.php(688): Bit3\Contao\ThemePlus\ThemePlus->parseStylesheets(Object(Contao\LayoutModel), Array)
#6 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\core\library\Contao\Controller.php(1823): Bit3\Contao\ThemePlus\ThemePlus->hookReplaceDynamicScriptTags('<!DOCTYPE html>...')
#7 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\core\classes\FrontendTemplate.php(99): Contao\Controller::replaceDynamicScriptTags('<!DOCTYPE html>...')
#8 C:\MAMP\htdocs\bernutz\contao-3.3.7\system\modules\core\pages\PageRegular.php(189): Contao\FrontendTemplate->output(true)
#9 C:\MAMP\htdocs\bernutz\contao-3.3.7\index.php(260): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#10 C:\MAMP\htdocs\bernutz\contao-3.3.7\index.php(444): Index->run()
#11 {main}

[15-Jan-2015 16:22:45 Europe/Berlin] PHP Fatal error: Uncaught exception 'RuntimeException' with message 'The source file "C:\MAMP\htdocs\bernutz\contao-3.3.7/�䗿o��E

**Comment by tristanlins** [comment]
Ach im Forum schau ich nicht immer nach :D

Hast du den uploadPath nachträglich geändert? Das sieht mir so aus.
Wenn ich mir den Code anschaue: https://github.com/bit3/contao-theme-plus/blob/support/4.x/src/Bit3/Contao/ThemePlus/ThemePlus.php#L1550-L1564

Dann läuft der in den IF Zweig nicht rein, weil in der Datei die filesource nicht mehr mit uploadPath überein stimmt. Anschließend übergibt er die UUID als Dateipfad und das kommt natürlich nicht hin.

Hat also nichts mit Theme+ direkt zu tun, sondern dass die Asset Konfiguration durch das Ändern von uploadPath einfach nicht mehr stimmt.

**Comment by akroii** [comment]
Man muss also Zwangsläufig eine eigene Asset Konfiguration vornehmen um eine geänderte uploadPath Variable zum laufen zu bekommen?

Wie sieht die Konfiguration dafür aus?

**Comment by tristanlins** [comment]
Nein, mit Asset Konfiguration meine ich die Konfiguration der konfigurierten Stylesheets und JavaScripts. D.h. im Endeffekt müsstest du nur jedes Asset öffnen, die "Quelle" neu auswählen und speichern.

**Comment by akroii** [comment]
Danke. :)

Ja ich hatte den UploadPath nachträglich geändert.

**Comment by tristanlins** [comment]
Ja das ist nicht vorgesehen, müsste man mal schauen ob man daran ggf. auf Dauer vielleicht noch was ändert, ich würde den Upload Path aber generell nicht ändern...
